#ifndef HEADER_FUNCIONES_H_INCLUDED
#define HEADER_FUNCIONES_H_INCLUDED

void nuevoIndiceProvincial(float indicesDeProvinciaPorRubro[CANTIDAD_PROVINCIAS][CANTIDAD_RUBROS]);


#endif // HEADER_FUNCIONES_H_INCLUDED
